In [3]:
import numpy as np
import tensorflow as tf
from sklearn.utils import shuffle

In [4]:
np.random.seed(0)
tf.set_random_seed(0)

M = 2 # 入力データの次元
K = 3 # クラス数
n = 100 # クラスごとのデータ数
N = n * K # 全データ数

In [8]:
''''データの生成'''
X1 = np.random.randn(n, M) + np.array([0, 10])
X2 = np.random.randn(n, M) + np.array([5, 5])
X3 = np.random.randn(n, M) + np.array([10, 0])
Y1 = np.array([[1, 0, 0] for i in range(n)])
Y2 = np.array([[0, 1, 0] for i in range(n)])
Y3 = np.array([[0, 0, 1] for i in range(n)])

X = np.concatenate((X1, X2, X3), axis=0)
Y = np.concatenate((Y1, Y2, Y3), axis=0)

'''モデル設定'''
W = tf.Variable(tf.zeros([M, K]))
b = tf.Variable(tf.zeros([K]))

x = tf.placeholder(tf.float32, shape=[None, M])
t = tf.placeholder(tf.float32, shape=[None, K])
y = tf.nn.softmax(tf.matmul(x, W) + b)

cross_entropy = tf.reduce_mean(-tf.reduce_sum(t * tf.log(y), axis=1))
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)

correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(t, 1))

In [9]:
'''モデル学習'''
# 初期化
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run (init)

batch_size = 50 # ミニバッチサイズ
n_batches = N // batch_size

# ミニバッチ学習
for epoch in range(20):
    X_, Y_ = shuffle(X, Y)
    
    for i in range(n_batches):
        start = i * batch_size
        end = start + batch_size
        
        sess.run(train_step, feed_dict={
            x: X_[start:end],
            t: Y_[start:end]
        })

'''学習結果の確認'''
X_, Y_ = shuffle(X, Y)

classified = correct_prediction.eval(session=sess, feed_dict={
    x: X_[0:10],
    t: Y_[0:10]
})
prob = y.eval(session=sess, feed_dict={
    x: X_[0:10]
})

print('classified: ')
print(classified)
print('output probability: ')
print(prob)

classified: 
[ True  True  True  True  True  True  True  True  True  True]
output probability: 
[[3.4595761e-03 9.8469037e-01 1.1850093e-02]
 [1.3855459e-01 8.6045957e-01 9.8581775e-04]
 [4.8616927e-02 9.5012766e-01 1.2553824e-03]
 [2.0425623e-02 9.6541417e-01 1.4160250e-02]
 [1.0882728e-10 7.2239432e-04 9.9927765e-01]
 [1.4310676e-02 9.7047025e-01 1.5219100e-02]
 [1.2195478e-08 1.0594313e-02 9.8940569e-01]
 [9.9417758e-01 5.8224434e-03 2.6782019e-09]
 [9.9448352e-09 6.2159384e-03 9.9378407e-01]
 [2.6385984e-03 9.1941208e-01 7.7949345e-02]]
